#!/bin/bash
# This is a simple script to keep the botcore running in the event of
# network disconnects.

# Copyright (c) Miga, 2015-2016.

# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do
# so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# The defines for the launcher. PWD_CORES leads to the cores directory,
# whereas BOTCORE is the bot that will be run.

PWD_CORES="$PWD/cores"

while true
do
	# This is here instead of with $PWD_CORES in the event that the core is
	# changed.
	BOTCORE=`cat $PWD/enabledcore`

	# change directory to the botcore to be run
	cd $PWD_CORES/$BOTCORE/

	# exec botcore script using bash
	bash botcore

	# If we get disconnected from the network for any reason, we'll retry.
	echo "Bot $BOTCORE disconnected from network, retrying."
	sleep 1
done
