#!/bin/bash
# Simple weather checker - uses AccuWeather.

[ -n "$1" ] || { echo "usage: weather <city or ZIP>"; exit 1; }

weather=`curl -s http://rss.accuweather.com/rss/liveweather_rss.asp\?metric\=1\&locCode\=$1 | grep "<description>Currently " | cut -d ">" -f2 | sed 's/ &#176;/°/'`
if [[ $weather = "" ]]
then
	printf "Could not determine the weather for that location, try by city name or ZIP code.\n"
else
	printf "$weather\n"
fi
