#!/bin/bash
# Simple weather checker - uses AccuWeather.

[ -n "$1" ] || { echo "usage: weather <city or ZIP>"; exit 1; }

curl -s http://rss.accuweather.com/rss/liveweather_rss.asp\?metric\=1\&locCode\=$1 | perl -ne 'if (/Currently/) {chomp;/\<title\>Currently: (.*)?\<\/title\>/; print "$1"; }'
echo ""
